AbstractTravelAgencyViewWeb/Controllers/ConditionsController.cs
using AbstractTravelAgencyServiceDAL.BindingModel;
using AbstractTravelAgencyServiceDAL.Interfaces;
using System.Web.Mvc;

namespace AbstractTravelAgencyViewWeb.Controllers
{
    public class ConditionsController : Controller
    {
        private IConditionService service = Globals.ConditionService;
        // GET: Conditions
        public ActionResult Index()
        {
            return View(service.GetList());
        }

        // GET: Conditions/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreatePost()
        {
            service.AddElement(new ConditionBindingModel
            {
                ConditionName = Request["ConditionName"]
            });
            return RedirectToAction("Index");
        }

        // GET: Conditions/Edit/5
        public ActionResult Edit(int id)
        {
            var viewModel = service.GetElement(id);
            var bindingModel = new ConditionBindingModel
            {
                Id = id,
                ConditionName = viewModel.ConditionName
            };
            return View(bindingModel);
        }

        [HttpPost]
        public ActionResult EditPost()
        {
            service.UpdElement(new ConditionBindingModel
            {
                Id = int.Parse(Request["Id"]),
                ConditionName = Request["ConditionName"]
            });
            return RedirectToAction("Index");
        }

        // GET: Conditions/Delete/5
        public ActionResult Delete(int id)
        {
            service.DelElement(id);
            return RedirectToAction("Index");
        }
    }
}

AbstractTravelAgencyViewWeb/Views/Conditions/Create.cshtml
@model AbstractTravelAgencyServiceDAL.BindingModel.ConditionBindingModel

@{
    ViewBag.Title = "Создание условия";
}

<h2>Создание условия</h2>


@using (Html.BeginForm("CreatePost", "Conditions", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class = "control-label col-md-2">Название</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConditionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConditionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку условий", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AbstractTravelAgencyViewWeb/Views/Conditions/Delete.cshtml
@model AbstractTravelAgencyServiceDAL.BindingModel.ConditionBindingModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ConditionBindingModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ConditionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConditionName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AbstractTravelAgencyViewWeb/Views/Conditions/Edit.cshtml
@model AbstractTravelAgencyServiceDAL.BindingModel.ConditionBindingModel

@{
    ViewBag.Title = "Изменение условия";
}

<h2>Изменение условия</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ConditionId)

        <div class="form-group">
            <label class = "control-label col-md-2">Название</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConditionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConditionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку условий", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AbstractTravelAgencyViewWeb/Views/Conditions/Index.cshtml
@model IEnumerable<AbstractTravelAgencyServiceDAL.ViewModel.ConditionViewModel>

@{
    ViewBag.Title = "Список условий";
}

<h2>Список условий</h2>

<p>
    @Html.ActionLink("Добавить условие", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ConditionName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ConditionName)
        </td>
        <td>
            @Html.ActionLink("Изменить", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>