AbstractTravelAgencyViewWeb/Controllers/CitiesController.cs
using AbstractTravelAgencyServiceDAL.BindingModel;
using AbstractTravelAgencyServiceDAL.Interfaces;
using System.Web.Mvc;

namespace AbstractTravelAgencyViewWeb.Controllers
{
    public class CitiesController : Controller
    {
        private ICityService service = Globals.CityService;

        public ActionResult List()
        {
            //ViewBag.Cities = service.GetList();
            return View(service.GetList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreatePost()
        {
            service.AddElement(new CityBindingModel
            {
                CityName = Request["CityName"]
            });
            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            var viewModel = service.GetElement(id);
            var bindingModel = new CityBindingModel
            {
                Id = id,
                CityName = viewModel.CityName
            };
            return View(bindingModel);
        }

        [HttpPost]
        public ActionResult EditPost()
        {
            service.UpdElement(new CityBindingModel
            {
                Id = int.Parse(Request["Id"]),
                CityName = Request["CityName"]
            });
            return RedirectToAction("List");
        }

        public ActionResult More(int id)
        {
            var viewModel = service.GetElement(id);
            
            return View(viewModel);
        }

        public ActionResult Delete(int id)
        {
            service.DelElement(id);
            return RedirectToAction("List");
        }
    }
}

AbstractTravelAgencyViewWeb/Views/Cities/Create.cshtml
@model AbstractTravelAgencyServiceDAL.BindingModel.CityBindingModel

@{
    ViewBag.Title = "Добавление города";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавление города</h2>


@using (Html.BeginForm("CreatePost", "Cities", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class = "control-label col-md-2">Название</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку городов", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AbstractTravelAgencyViewWeb/Views/Cities/Edit.cshtml
@model AbstractTravelAgencyServiceDAL.BindingModel.CityBindingModel

@{
    ViewBag.Title = "Изменение города";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Изменение города</h2>


@using (Html.BeginForm("EditPost", "Cities", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>StorageBindingModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку городов", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AbstractTravelAgencyViewWeb/Views/Cities/List.cshtml
@model IEnumerable<AbstractTravelAgencyServiceDAL.ViewModel.CityViewModel>

@{
    ViewBag.Title = "Список городов";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Список городов</h2>

<p>
    @Html.ActionLink("Добавить город", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CityName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CityName)
            </td>
            <td>
                @Html.ActionLink("Изменить", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.Id }) |
                @Html.ActionLink("Подробнее", "More", new { id = item.Id })
            </td>
        </tr>
    }

</table>

AbstractTravelAgencyViewWeb/Views/Cities/More.cshtml
@model AbstractTravelAgencyServiceDAL.ViewModel.CityViewModel

@{
    ViewBag.Title = "Подробнее";
}

<h2>Подробнее</h2>

<div>
    <table class="table">
        <tr>
            <th>
                <label>Условие</label>
            </th>
            <th>
                <label>Количество</label>
            </th>
        </tr>

        @foreach (var item in Model.CityConditions)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ConditionName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td></td>
        </tr>
        }

    </table>
</div>
<p>
    @Html.ActionLink("Изменить", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Вернуться к списку городов", "List")
</p>